### ISSUE TITLE
Using the redis connection inside a subscription trigger

### ISSUE THREAD

**Issue by jmoriau** [stefanwille/crystal-redis-examples#2]
Hello,

Today I tried to do this:

``` ruby
redis = Redis.new
redis.subscribe("channel") do |on|
  on.message do |channel, message|
    #react to this trigger by querying redis.
     x = redis.smembers("blabla)" #<<< This will raise an exception (see below)    
  end
end
```

``` shell
Unhandled exception:
cast from Nil to Array(Redis::RedisValue) failed, at /home/app/libs/redis/redis/command_execution/value_oriented.cr:48 (TypeCastError)
[4800679] *CallStack::unwind:Array(Pointer(Void)) +87
[4800570] *CallStack#initialize:Array(Pointer(Void)) +10
[4800522] *CallStack::new:CallStack +42
[4731560] *raise<TypeCastError>:NoReturn +24
[5425501] *Redis +493
[5424989] *Redis +157
```

I have to use another redis connection inside the subscribe block so I just wanted to know if this was by design or not :smile: 

Thanks!

**Comment by stefanwille** [comment]
Hello,

let me quote the Redis documentation: 

> A client subscribed to one or more channels should not issue commands, although it can subscribe and unsubscribe to and from other channels.

(from http://redis.io/topics/pubsub)

It is expected that you have to use a second connection to send commands. Though it would be nice if crystal-redis would produce a nicer error message otherwise.

**Comment by jmoriau** [comment]
Hi,
Yeah I figured it a while ago but couldn't find the issue! Completely forgot I posted in the examples instead of the real repo!

Sorry!
